### ISSUE TITLE
docker run with Error: Cannot find module '/usr/src/app/setupProxy.js'

### ISSUE THREAD

**Issue by geosmart** [MarquezProject/marquez-web#111]
```bash
[root@k8s marquez-web-0.0.1]# docker build -t marquez-web .
Sending build context to Docker daemon  1.281MB
Step 1/9 : FROM node:11
 ---> 5b97b72da029
Step 2/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> ce65b415b82a
Step 3/9 : COPY package*.json ./
 ---> Using cache
 ---> aebd0493872d
Step 4/9 : RUN npm install
 ---> Using cache
 ---> e15263e20e4e
Step 5/9 : COPY . .
 ---> Using cache
 ---> f65d969c8887
Step 6/9 : RUN npm run build
 ---> Using cache
 ---> 63a3f5a2de88
Step 7/9 : COPY docker/entrypoint.sh entrypoint.sh
 ---> Using cache
 ---> e1bb2c685141
Step 8/9 : EXPOSE 3000
 ---> Using cache
 ---> 03a2b219fc80
Step 9/9 : ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
 ---> Using cache
 ---> 54177606b501
Successfully built 54177606b501
Successfully tagged marquez-web:latest
[root@k8s marquez-web-0.0.1]# docker run -p 3000:3000  marquez-web
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/usr/src/app/setupProxy.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by wslulciuc** [comment]
We recently added a [quickstart section](https://github.com/MarquezProject/marquez-web#quickstart), mind giving that a try? Let us know if you are still seeing this error!

**Comment by wslulciuc** [comment]
@geosmart: We are moving all discussions to https://github.com/MarquezProject/marquez. Let us know if you are still running into this issue.
